'use client';
import modelParams from '@/lib/model/model_params.v1.json';
import { METFORMIN_OPTIONS, DISCHARGE_OPTIONS } from '@/lib/model/encodings';
import type { FormData } from './page';
import { getTypicalText, getYesNoText } from './page';
const { feature_ranges } = modelParams;
function NI({label,value,onChange,feature,typical}:{label:string;value:string;onChange:(v:string)=>void;feature:string;typical:string}){const r=feature_ranges[feature as keyof typeof feature_ranges];const id=`i-${feature}`;return(<div><label htmlFor={id} className="block text-sm font-medium text-slate-700 mb-1">{label}</label><input id={id} type="number" inputMode="numeric" step="1" min={r.min} max={r.max} value={value} onChange={e=>onChange(e.target.value)} className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm text-slate-900 bg-white focus:ring-2 focus:ring-blue-500 focus:border-blue-500"/>{typical&&<p className="mt-1 text-xs text-slate-500">{typical}</p>}</div>);}
const bc=(a:boolean)=>`px-4 py-2 rounded-lg border text-sm font-medium transition-colors ${a?'bg-blue-600 text-white border-blue-600':'bg-white text-slate-700 border-slate-300 hover:border-blue-300'}`;
const sel="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm text-slate-900 bg-white focus:ring-2 focus:ring-blue-500 focus:border-blue-500";
interface Props{step:number;form:FormData;updateField:(f:keyof FormData,v:string)=>void;}
export function CalculatorStep({step,form,updateField:u}:Props){switch(step){
case 1:return<NI label="Prior inpatient stays in the past year" value={form.number_inpatient} onChange={v=>u('number_inpatient',v)} feature="number_inpatient" typical={getTypicalText('number_inpatient')}/>;
case 2:return<NI label="Emergency visits in the past year" value={form.number_emergency} onChange={v=>u('number_emergency',v)} feature="number_emergency" typical={getTypicalText('number_emergency')}/>;
case 3:return<NI label="Number of diagnoses recorded" value={form.number_diagnoses} onChange={v=>u('number_diagnoses',v)} feature="number_diagnoses" typical={getTypicalText('number_diagnoses')}/>;
case 4:return<NI label="Number of distinct medications given this stay" value={form.num_medications} onChange={v=>u('num_medications',v)} feature="num_medications" typical={getTypicalText('num_medications')}/>;
case 5:return<div className="space-y-4"><NI label="Number of lab procedures" value={form.num_lab_procedures} onChange={v=>u('num_lab_procedures',v)} feature="num_lab_procedures" typical={getTypicalText('num_lab_procedures')}/><NI label="Number of other procedures" value={form.num_procedures} onChange={v=>u('num_procedures',v)} feature="num_procedures" typical={getTypicalText('num_procedures')}/></div>;
case 6:return<div className="space-y-4"><div><label className="block text-sm font-medium text-slate-700 mb-1">Is the patient on any diabetes medication?</label><div className="flex gap-4"><button type="button" className={bc(form.diabetesMed==='1')} onClick={()=>u('diabetesMed','1')}>Yes</button><button type="button" className={bc(form.diabetesMed==='0')} onClick={()=>u('diabetesMed','0')}>No</button></div><p className="mt-1 text-xs text-slate-500">{getYesNoText('diabetesMed')}</p></div>{form.diabetesMed==='1'&&<div><label htmlFor="met" className="block text-sm font-medium text-slate-700 mb-1">Metformin status</label><select id="met" value={form.metformin} onChange={e=>u('metformin',e.target.value)} className={sel}><option value="">Select...</option>{METFORMIN_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div>}</div>;
case 7:return<div><label className="block text-sm font-medium text-slate-700 mb-1">Is the primary diagnosis respiratory?</label><div className="flex gap-4"><button type="button" className={bc(form.diag_1_Respiratory==='1')} onClick={()=>u('diag_1_Respiratory','1')}>Yes</button><button type="button" className={bc(form.diag_1_Respiratory==='0')} onClick={()=>u('diag_1_Respiratory','0')}>No</button></div><p className="mt-1 text-xs text-slate-500">{getYesNoText('diag_1_Respiratory')}</p></div>;
case 8:return<div><label htmlFor="dsc" className="block text-sm font-medium text-slate-700 mb-1">Discharge destination</label><select id="dsc" value={form.dischargeDestination} onChange={e=>u('dischargeDestination',e.target.value)} className={sel}>{DISCHARGE_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><p className="mt-1 text-xs text-slate-500">Most patients: Home / other</p></div>;
case 9:return<div className="space-y-4"><p className="text-sm text-slate-600 italic">Optional — clinical context, NOT used in the risk score</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label htmlFor="ht" className="block text-sm font-medium text-slate-700 mb-1">Height (cm)</label><input id="ht" type="number" min="50" max="250" value={form.height} onChange={e=>u('height',e.target.value)} className={sel} placeholder="e.g. 170"/></div><div><label htmlFor="wt" className="block text-sm font-medium text-slate-700 mb-1">Weight (kg)</label><input id="wt" type="number" min="20" max="300" value={form.weight} onChange={e=>u('weight',e.target.value)} className={sel} placeholder="e.g. 70"/></div><div><label htmlFor="sys" className="block text-sm font-medium text-slate-700 mb-1">Systolic BP (mmHg)</label><input id="sys" type="number" min="60" max="300" value={form.systolic} onChange={e=>u('systolic',e.target.value)} className={sel} placeholder="e.g. 120"/></div><div><label htmlFor="dia" className="block text-sm font-medium text-slate-700 mb-1">Diastolic BP (mmHg)</label><input id="dia" type="number" min="30" max="200" value={form.diastolic} onChange={e=>u('diastolic',e.target.value)} className={sel} placeholder="e.g. 80"/></div></div></div>;
default:return null;}}